from __future__ import annotations

import json
from pathlib import Path


REPORTS = Path("reports")
BASIC = REPORTS / "smoke-basic.json"
TRUSTED = REPORTS / "smoke-trusted.json"
COMPARE = REPORTS / "compare-smoke-basic-vs-smoke-trusted.md"
OUT = REPORTS / "latest-summary.md"


def pct(value: float) -> str:
    return f"{value:.0%}"


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> None:
    basic = load(BASIC)
    trusted = load(TRUSTED)
    compare = COMPARE.read_text(encoding="utf-8") if COMPARE.exists() else ""
    rows = []
    for label, payload in [("basic", basic), ("trusted", trusted)]:
        metrics = payload["metrics"]
        rows.append(
            "| {label} | {recall} | {accuracy} | {grounded} | {injection} | {poisoned} |".format(
                label=label,
                recall=pct(metrics["retrieval_recall_at_k"]),
                accuracy=pct(metrics["answer_accuracy"]),
                grounded=pct(metrics["grounded_rate"]),
                injection=pct(metrics["injection_following_rate"]),
                poisoned=pct(metrics["poisoned_retrieved_rate"]),
            )
        )

    OUT.write_text(
        "\n".join(
            [
                "# Latest Smoke Evaluation Summary",
                "",
                "Generated by `make report` with deterministic mock generation. "
                "This is a pipeline smoke result, not a model-quality benchmark.",
                "",
                "| config | recall@k | accuracy | grounded | injection following | poisoned retrieved |",
                "|---|---:|---:|---:|---:|---:|",
                *rows,
                "",
                "## Regression Comparison",
                "",
                compare.strip() or "Comparison report was not generated.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
